uploads = []
outputs = []

[[generated]]
id = "gbRVnf-EocG0ZY-zr7wgB"
uri = "file://artifacts/cocos-life/src/assets/hero.png"
type = "image"
title = "Fresh coconut on wooden table"

[[generated]]
id = "4_oNLem1_GjzpOCJV6JQq"
uri = "file://artifacts/cocos-life/src/assets/agua-de-coco.png"
type = "image"
title = "Bottle of coconut water"

[[generated]]
id = "ZzZoZTyxhfTk095lRtj6s"
uri = "file://artifacts/cocos-life/src/assets/pulpa-de-coco.png"
type = "image"
title = "Bowl of fresh coconut pulp"

[[generated]]
id = "LudP2F8-dn8AhwJ3bDUZh"
uri = "file://artifacts/cocos-life/src/assets/aceite-de-coco.png"
type = "image"
title = "Jar of pure coconut oil"

[[generated]]
id = "y7GxTwlWNWd1drFEJQJ4G"
uri = "file://artifacts/cocos-life/src/assets/leche-de-coco.png"
type = "image"
title = "Glass of creamy coconut milk"

[[generated]]
id = "AFBCOK93Q64VRp_P9ws1x"
uri = "file://artifacts/cocos-life/src/assets/mantequilla-de-coco.png"
type = "image"
title = "Jar of creamy coconut butter"
